export default [
  {
    name: "OBJECTID",
    type: "esriFieldTypeOID",
    alias: "OBJECTID",
    domain: null,
  },
  {
    name: "RouteID",
    type: "esriFieldTypeString",
    alias: "RouteID",
    length: 12,
    domain: null,
  },
  {
    name: "ARM",
    type: "esriFieldTypeSingle",
    alias: "ARM",
    domain: null,
  },
  {
    name: "SRMP",
    type: "esriFieldTypeSingle",
    alias: "SRMP",
    domain: null,
  },
  {
    name: "Direction",
    type: "esriFieldTypeString",
    alias: "Direction",
    length: 2,
    domain: null,
  },
  {
    name: "Easting",
    type: "esriFieldTypeDouble",
    alias: "Easting",
    domain: null,
  },
  {
    name: "Northing",
    type: "esriFieldTypeDouble",
    alias: "Northing",
    domain: null,
  },
  {
    name: "Longitude",
    type: "esriFieldTypeDouble",
    alias: "Longitude",
    domain: null,
  },
  {
    name: "Latitude",
    type: "esriFieldTypeDouble",
    alias: "Latitude",
    domain: null,
  },
  {
    name: "Azimuth",
    type: "esriFieldTypeSmallInteger",
    alias: "Azimuth",
    domain: null,
  },
  {
    name: "StateRouteNumber",
    type: "esriFieldTypeString",
    alias: "StateRouteNumber",
    length: 3,
    domain: null,
  },
  {
    name: "RelRouteType",
    type: "esriFieldTypeString",
    alias: "RelRouteType",
    length: 2,
    domain: null,
  },
  {
    name: "RelRouteQual",
    type: "esriFieldTypeString",
    alias: "RelRouteQual",
    length: 7,
    domain: null,
  },
  {
    name: "AheadBackInd",
    type: "esriFieldTypeString",
    alias: "AheadBackInd",
    length: 1,
    domain: null,
  },
  {
    name: "LRS_Date",
    type: "esriFieldTypeString",
    alias: "LRS_Date",
    length: 8,
    domain: null,
  },
  {
    name: "SHAPE",
    type: "esriFieldTypeGeometry",
    alias: "SHAPE",
    domain: null,
  },
] as const;
