# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# Node.js
# This section defines the Azure Pipeline configuration for a Node.js project.
# It includes instructions for building the project using npm and saving the build artifacts.

# The trigger section specifies which branches will trigger the pipeline when new commits are pushed.
trigger:
  branches:
    include:
      - "master"
  tags:
    include:
      - "release/**"
      - "qa/**"
      - "dev/**"

# The pool section specifies the agent pool that will run the jobs in this pipeline.
# 'Default' is typically the name of the Microsoft-hosted agent pool provided by Azure DevOps.
pool:
  name: Default

# The stages section allows you to organize the pipeline into multiple stages.
# Here we have only one stage named 'build', which contains the jobs for building the project.
stages:
  - stage: build
    # Within the build stage, we define the jobs that need to be run.
    # Each job runs independently and can run on different agents if required.
    # The 'build' stage is responsible for executing tasks that compile and build the code.
    jobs:
      - job: installAndBuild
        displayName: Install and Build
        steps:
          - pwsh: |
              # Get the version of Node that is currently install.
              $node_version = [semver]([regex]::Match((node --version), '(?<=v).+').Value)

              # Specify the minimum required version
              $min_required_version = [semver]'20.0.0'

              if ($node_version -lt $min_required_version) {
                Write-Warning "Node version $node_version is less than $min_required_version. Please upgrade Node to continue."
              } else {
                Write-Host "Currently installed Node version $is node_version which meets the minimum requirement of $min_required_version."
              }
            name: check_node_version
            displayName: Check Node Version
            continueOnError: true

          # TODO: Only install Node if it is not LTS

          # Install the LTS version of Node
          # Version 16 was on the build agent rather than LTS.
          - task: UseNode@1
            name: use_node
            displayName: Install Node
            inputs:
              version: 20.X

          - task: Npm@1
            name: install_bun
            displayName: Install bun using NPM
            inputs:
              command: "custom"
              customCommand: "install -g bun"
              verbose: true

          # Install project dependencies using bun.
          - script: |
              bun install --frozen-lockfile
            name: bun_install
            displayName: Install dependencies

          # Run tests using bun.
          #
          # Note that this is `bun run test`,
          # different than `bun test`, bun's native
          # tesing tool. Not all of our tests work
          # with `bun test` yet.
          - script: |
              bun run test
            name: test
            continueOnError: true
            displayName: Run tests

          - task: PublishTestResults@2
            name: publish_test_results
            displayName: Publish Test Results
            condition: succeededOrFailed()
            continueOnError: true
            inputs:
              searchFolder: ./test-results
              testResultsFiles: test-results.xml

          # This task is disabled for the moment because enabling coverage causes
          # the unit test to run forever after mocking was added.
          # The issue is that mocking is not implemented for all URLs, so once that
          # has been completed then this task can be enabled again.
          - task: PublishCodeCoverageResults@2
            enabled: false
            name: publish_code_coverage
            displayName: Publish Code Coverage
            continueOnError: true
            inputs:
              summaryFileLocation: coverage/cobertura-coverage.xml

          # Run the package.json "build" script to compile the project.
          - script: |
              bun --bun run build
            name: build
            displayName: Build app
            # Sets the current working directory for this task to the sources directory.
            workingDirectory: $(Build.SourcesDirectory)

          # Copy the build output (dist folder) to the staging directory for artifact publishing.
          - task: CopyFiles@2
            name: copy_files
            displayName: Copy Files to $(Build.ArtifactStagingDirectory)
            inputs:
              # The target folder to copy files to, typically a staging directory for artifacts.
              TargetFolder: $(Build.ArtifactStagingDirectory)
              # The contents to copy, in this case, everything from the 'dist' folder.
              Contents: dist/**

          # Publish the build artifacts to Azure Pipelines.
          - task: PublishBuildArtifacts@1
            name: publish_build_artifacts
            displayName: Publish Build Artifacts
            inputs:
              # The path to the folder containing build artifacts to publish.
              PathtoPublish: $(Build.ArtifactStagingDirectory)
              # The name for this artifact, which can be used for deployment or reference.
              ArtifactName: www
