/* eslint-env: node */

/**
 * Tests the functions that convert from GitHub repo URLs to
 * Github Pages URLs and vice-versa.
 */

import { expect, test, describe } from "vitest";
import {
  getGithubUrlFromGithubPages,
  getGithubPagesUrlFromGithubRepoUrl,
  isGithubRepoUrl,
} from "../src/common/Github-Link";

const pagesUrl = "https://wsdot-gis.github.io/wsdot-mp-map";
const repoUrl = "https://github.com/WSDOT-GIS/wsdot-mp-map";

// Create regular expressions to match the expected responses.
const [pagesRe, repoRe] = [pagesUrl, repoUrl].map(
  (url) =>
    new RegExp(
      // Add optional trailing slash.
      String.raw`${url}\/?`
        // Excape the periods so they won't match any character.
        .replace(".", String.raw`\.`),
      // Make case-insensitive
      "i"
    )
);

test("create github repo link", () => {
  const outputUrl = getGithubUrlFromGithubPages(undefined, pagesUrl);
  expect(outputUrl).toMatch(repoRe);
});

test("create github pages link", () => {
  const outputUrl = getGithubPagesUrlFromGithubRepoUrl(undefined, repoUrl);
  expect(outputUrl).toMatch(pagesRe);
});

// Generated by CodiumAI

describe("isGithubRepoUrl", () => {
  // Returns true for a valid GitHub repository URL
  test("should return true for a valid GitHub repository URL", () => {
    const url = "https://github.com/org/repo";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(true);
  });

  // Returns true for a valid GitHub repository URL with uppercase letters
  test("should return true for a valid GitHub repository URL with uppercase letters", () => {
    const url = "https://github.com/ORG/REPO";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(true);
  });

  // Returns true for a valid GitHub repository URL with numbers
  test("should return true for a valid GitHub repository URL with numbers", () => {
    const url = "https://github.com/org123/repo456";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(true);
  });

  // Returns false for an empty string
  test("should return false for an empty string", () => {
    const url = "";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(false);
  });

  // Returns false for a URL with an invalid domain
  test("should return false for a URL with an invalid domain", () => {
    const url = "https://example.com/org/repo";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(false);
  });

  // Returns false for a URL with an invalid path
  test("should return false for a URL with an invalid path", () => {
    const url = "https://github.fake.cn/org/repo";
    const result = isGithubRepoUrl(url);
    expect(result).toBe(false);
  });
});
